//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interview.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_add_admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_add_admin()
        {
            this.schedule1 = new HashSet<schedule1>();
            this.techpannels = new HashSet<techpannel>();
        }
    
        public int Candidate_id { get; set; }
        public string candidateName { get; set; }
        public string pSkills { get; set; }
        public string sSkills { get; set; }
        public Nullable<byte> experience { get; set; }
        public string qualification { get; set; }
        public string designation { get; set; }
        public string noticeperiod { get; set; }
        public string clocation { get; set; }
        public string passwordC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schedule1> schedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<techpannel> techpannels { get; set; }
    }
}
