//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interview.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule1
    {
        public int Schedule_id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public Nullable<int> Interview_Id { get; set; }
        public Nullable<int> HRrating { get; set; }
        public Nullable<System.DateTime> hrIS { get; set; }
        public Nullable<bool> FinalStatus { get; set; }
    
        public virtual c_add_admin c_add_admin { get; set; }
        public virtual techpannel techpannel { get; set; }
    }
}
